# services:
#   postgres:
#     image: postgres:latest
#     restart: always
#     environment:
#       - POSTGRES_USER=${DB_USER}
#       - POSTGRES_PASSWORD=${DB_PASSWORD}
#     volumes:
#       - postgres:/var/lib/postgresql/data
#     ports:
#       - '${DB_PORT}:5432'

# volumes:
#   postgres:

services:
  api:
    build: .
    container_name: mrkt_api
    ports:
      - 8080:8080
    env_file:
      - .env
